(function(){
  const MINT='9LdFxvn2cMY2T6NDj3naThMhRUg7punCg6hAK5uXpump';
  const API=`https://api.dexscreener.com/token-pairs/v1/solana/${MINT}`;
  const money=value=>{const n=Number(value)||0;return n>=1e6?`$${(n/1e6).toFixed(2)}M`:n>=1e3?`$${(n/1e3).toFixed(1)}K`:`$${n.toFixed(2)}`};
  const price=value=>{const n=Number(value)||0;return n>=1?`$${n.toFixed(2)}`:n>=.01?`$${n.toFixed(4)}`:`$${n.toFixed(7)}`};
  const safe=value=>String(value||'').replace(/[&<>"']/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[char]));
  function mount(){const host=document.querySelector('.treasury-summary');if(!host||document.querySelector('.token-market'))return null;const panel=document.createElement('section');panel.className='token-market';panel.innerHTML=`<header><div><i></i><b>$CELLUMO / SOL</b><span>LIVE MARKET</span></div><a href="https://pump.fun/coin/${MINT}" target="_blank" rel="noopener noreferrer">TRADE ↗</a></header><div class="token-market-grid"><article><small>PRICE USD</small><strong data-market="price">SYNCING</strong><em data-market="change">24H —</em></article><article><small>PRICE SOL</small><strong data-market="sol">SYNCING</strong><em>LIVE QUOTE</em></article><article><small>MARKET CAP</small><strong data-market="cap">SYNCING</strong><em>FULLY DILUTED</em></article><article><small>LIQUIDITY</small><strong data-market="liquidity">SYNCING</strong><em data-market="dex">PRIMARY POOL</em></article><article><small>24H VOLUME</small><strong data-market="volume">SYNCING</strong><em>PRIMARY POOL</em></article><article><small>24H ORDERS</small><strong data-market="orders">SYNCING</strong><em>BUYS / SELLS</em></article></div><footer><span data-market="status">CONNECTING TO MARKET DATA</span><a data-market="pair" href="https://dexscreener.com/solana/${MINT}" target="_blank" rel="noopener noreferrer">DEXSCREENER ↗</a></footer>`;host.querySelector('.subhead')?.after(panel);return panel}
  async function refresh(){const panel=mount();if(!panel)return;try{const response=await fetch(API,{cache:'no-store'});if(!response.ok)throw new Error(`HTTP ${response.status}`);const pairs=await response.json();const pair=(Array.isArray(pairs)?pairs:[]).filter(item=>item.baseToken?.address===MINT).sort((a,b)=>(Number(b.liquidity?.usd)||0)-(Number(a.liquidity?.usd)||0))[0];if(!pair)throw new Error('pair unavailable');const set=(key,value)=>{const node=panel.querySelector(`[data-market="${key}"]`);if(node)node.textContent=value};const change=Number(pair.priceChange?.h24)||0;set('price',price(pair.priceUsd));set('change',`24H ${change>=0?'+':''}${change.toFixed(2)}%`);set('sol',`${Number(pair.priceNative||0).toFixed(9)} SOL`);set('cap',money(pair.marketCap||pair.fdv));set('liquidity',money(pair.liquidity?.usd));set('dex',`${String(pair.dexId||'DEX').toUpperCase()} PRIMARY`);set('volume',money(pair.volume?.h24));set('orders',`${Number(pair.txns?.h24?.buys||0).toLocaleString()} / ${Number(pair.txns?.h24?.sells||0).toLocaleString()}`);set('status',`LIVE · ${new Date().toLocaleTimeString('en-US',{timeZone:'America/New_York',hour12:false})} ET`);const link=panel.querySelector('[data-market="pair"]');if(link)link.href=safe(pair.url)}catch(error){setTimeout(refresh,5000);const status=panel.querySelector('[data-market="status"]');if(status)status.textContent=`MARKET DATA RETRYING · ${error.message}`}}
  refresh();setInterval(refresh,15000);
})();